name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/bilalalpaslan/gdsc-chatbot
    
    - name: Push image registery
      run: docker push ghcr.io/bilalalpaslan/gdsc-chatbot
